tinyMCE.addI18n('ru.emotions_dlg',{
title:"Вставить смайл",
desc:"Смайлы",
confused:"Сконфуженный",
cool:"Круто",
cry:"Плачет",
eek:"Eek",
embarassed:"Смущенный",
evil:"Злой",
frown:"Нахмуренный",
grin:"Усмехающийся",
laughing:"Смеётся",
mad:"Безумный",
neutral:"Нейтральный",
roll:"Закативший глаза",
sad:"Грустный",
smile:"Улыбка",
surprised:"Удивлённый",
tongue_out:"Высунул язык",
wink:"Подмигивающий",
yell:"Кричит"
});